version: '3.9'

services:

  httpd:
    image: nginx-openresty-oidc
    container_name: nginx-openresty-oidc
    restart: always
    volumes:
      - "./openresty/conf.d:/etc/nginx/conf.d"
      - "./openresty/html:/usr/local/openresty/nginx/html"
  
    environment:
      - TZ="Europe/Berlin"
    ports:
      - "80:80"
      - "443:443"
